services:
  - type: web
    name: cinema-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: HF_API_TOKEN
        sync: false
      - key: WEBHOOK_URL
  value: "https://30d494270f6118b157ff746577891acc.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11.9"
